import React, { useState } from 'react';
import { Button } from './ui/button';
import { AlertCircle, CheckCircle, AlertTriangle, Copy, Check } from 'lucide-react';
import { generateSafetyChecklist } from '../utils/safetyChecklist';

const getSeverityColor = (severity) => {
  switch (severity) {
    case 'critical':
      return 'text-red-600 bg-red-50 border-red-200';
    case 'caution':
      return 'text-yellow-700 bg-yellow-50 border-yellow-200';
    default:
      return 'text-green-700 bg-green-50 border-green-200';
  }
};

const getSeverityIcon = (severity) => {
  switch (severity) {
    case 'critical':
      return AlertCircle;
    case 'caution':
      return AlertTriangle;
    default:
      return CheckCircle;
  }
};

const ResultsView = ({ diagnoses, contextFlags, observations }) => {
  const [showSecondary, setShowSecondary] = useState(false);
  const [copied, setCopied] = useState(false);

  const primary = diagnoses.primary;
  const secondary = diagnoses.secondary;
  const safetyChecklist = generateSafetyChecklist(
    primary.severity,
    primary.diagnosis.id,
    contextFlags
  );

  const handleExport = () => {
    const exportText = `
CARSCAN DIAGNOSTIC REPORT
========================

PRIMARY DIAGNOSIS:
${primary.diagnosis.label}
Likelihood: ${Math.round(primary.likelihood * 100)}%
Severity: ${primary.severity.toUpperCase()}

${secondary ? `SECONDARY POSSIBILITY:
${secondary.diagnosis.label}
Likelihood: ${Math.round(secondary.likelihood * 100)}%

` : ''}SAFETY GUIDANCE:
${safetyChecklist.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${observations.filter(o => o.state === 'active' || o.state === 'resolved').length > 0 ? `
OBSERVATIONS:
${observations.filter(o => o.state === 'active' || o.state === 'resolved').map(o => 
  `- [${o.state.toUpperCase()}] ${o.tags.join(', ')}${o.note ? ': ' + o.note : ''}`
).join('\n')}
` : ''}
Generated by CarScan
    `.trim();

    navigator.clipboard.writeText(exportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const SeverityIcon = getSeverityIcon(primary.severity);

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Primary Diagnosis */}
      <div className={`p-6 rounded-xl border-2 ${getSeverityColor(primary.severity)}`}>
        <div className="flex items-start gap-4">
          <div className="flex-shrink-0">
            <SeverityIcon className="h-8 w-8" />
          </div>
          <div className="flex-1 space-y-3">
            <div>
              <h3 className="text-xl font-semibold mb-1">{primary.diagnosis.label}</h3>
              <p className="text-sm opacity-90">Likelihood: {Math.round(primary.likelihood * 100)}%</p>
            </div>
            <div className="pt-2 border-t border-current/20">
              <p className="text-sm font-medium uppercase tracking-wide mb-1">Severity</p>
              <p className="text-base font-semibold">{primary.severity}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Secondary Diagnosis */}
      {secondary && (
        <div className="space-y-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowSecondary(!showSecondary)}
            className="text-sm text-slate-600 hover:text-slate-900"
          >
            {showSecondary ? 'Hide' : 'Show'} secondary possibility
          </Button>
          {showSecondary && (
            <div className="p-4 rounded-xl border-2 border-slate-200 bg-slate-50">
              <h4 className="font-semibold text-slate-900 mb-1">{secondary.diagnosis.label}</h4>
              <p className="text-sm text-slate-600">Likelihood: {Math.round(secondary.likelihood * 100)}%</p>
            </div>
          )}
        </div>
      )}

      {/* Commonly Mistaken For */}
      {diagnoses.commonMistakenFor && diagnoses.commonMistakenFor.length > 0 && (
        <div className="p-4 rounded-xl bg-blue-50 border border-blue-200">
          <h4 className="font-semibold text-blue-900 mb-2">Commonly mistaken for:</h4>
          <ul className="space-y-1">
            {diagnoses.commonMistakenFor.map((item, i) => (
              <li key={i} className="text-sm text-blue-800">• {item}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Safety Checklist */}
      {safetyChecklist.length > 0 && (
        <div className="p-6 rounded-xl bg-slate-50 border-2 border-slate-200">
          <h4 className="font-semibold text-slate-900 mb-4 text-lg">Safety Checklist</h4>
          <ol className="space-y-3">
            {safetyChecklist.map((item, i) => (
              <li key={i} className="flex gap-3 text-slate-700">
                <span className="flex-shrink-0 font-semibold text-slate-500">{i + 1}.</span>
                <span className="text-base">{item}</span>
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Critical Warning */}
      {primary.severity === 'critical' && (
        <div className="p-4 rounded-xl bg-red-50 border-2 border-red-300">
          <h4 className="font-semibold text-red-900 mb-2 flex items-center gap-2">
            <AlertCircle className="h-5 w-5" />
            Why This Matters
          </h4>
          <p className="text-sm text-red-800">
            This is a critical safety issue. Do not continue driving if you suspect serious engine, brake, or cabin-fume problems. Serious harm or loss of control is possible.
          </p>
        </div>
      )}

      {/* Export Button */}
      <div className="pt-4">
        <Button
          onClick={handleExport}
          variant="outline"
          size="lg"
          className="w-full h-12 border-2 border-slate-300 hover:border-slate-400 hover:bg-slate-50"
        >
          {copied ? (
            <>
              <Check className="h-5 w-5 mr-2" />
              Copied to clipboard!
            </>
          ) : (
            <>
              <Copy className="h-5 w-5 mr-2" />
              Copy summary for mechanic
            </>
          )}
        </Button>
      </div>
    </div>
  );
};

export default ResultsView;
